const allDatabase = {
  "shops": {
    "categories": {
      "shop-skeleton": "骷髏頓的商店",
      "shop-market": "鬼燈市集",
      "shop-restaurant": "餐館",
      "shop-bobblehead": "搖頭娃娃商店",
      "shop-curio": "詭異珍品"
    },
    "items": {
      "shop-skeleton": [
        { "item_id": "蝙蝠鏢 BATIKANS", "category": "武器裝備", "stock": "大量", "cost": "20 個 5 CCP" },
        { "item_id": "發條箭 CLOCKWORK ARROWS", "category": "武器裝備", "stock": "限量", "cost": "5 支 200 CCP" },
        { "item_id": "發條盾 CLOCKWORK SHIELD", "category": "武器裝備", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "鱷魚箭 CROCARROW", "category": "武器裝備", "stock": "限量", "cost": "5 支 100 CCP" },
        { "item_id": "聖化戰斧 HALLOWED AXE", "category": "武器裝備", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "聖化短弓 HALLOWED BOW", "category": "武器裝備", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "聖化匕首 HALLOWED DAGGER", "category": "武器裝備", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "聖化盾牌 HALLOWED SHIELD", "category": "武器裝備", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "聖化短劍 HALLOWED SWORD", "category": "武器裝備", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "提燈盾 LANTERN SHIELD", "category": "武器裝備", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "閃電棒 LIGHTNING ROD", "category": "武器裝備", "stock": "限量", "cost": "150 CCP" },
        { "item_id": "南瓜炸彈 PUMPKIN BOMB", "category": "武器裝備", "stock": "大量", "cost": "50 CCP" },
        { "item_id": "尖嘯箭矢 SCREAMING ARROWS", "category": "武器裝備", "stock": "大量", "cost": "20 支 100 CCP" },
        { "item_id": "鍍銀柯爾特子彈 SILVERED COLT ROUNDS", "category": "武器裝備", "stock": "稀缺", "cost": "500 CCP" },
        { "item_id": "狼皮手套 WOLF GLOVES", "category": "武器裝備", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "木樁 WOODEN STAKE", "category": "武器裝備", "stock": "限量", "cost": "25 CCP" },
        { "item_id": "蝙蝠肉乾 BAT JERKY", "category": "消耗品", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "血酒瓶 BLOOD FLASK", "category": "消耗品", "stock": "限量", "cost": "125 CCP" },
        { "item_id": "血酒 BLOOD WINE", "category": "消耗品", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "大釜水 CAULDRON WATER", "category": "消耗品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "死亡棒 DEATH STICKS", "category": "消耗品", "stock": "限量", "cost": "10 CCP" },
        { "item_id": "新鮮南瓜 FRESH PUMPKIN", "category": "消耗品", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "漏斗網蛋糕 FUNNEL WEB CAKE", "category": "消耗品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "傑克南瓜燈種子 JACK-O-LANTERN SEEDS", "category": "消耗品", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "南瓜潘趣酒 PUMPKIN PUNCH", "category": "消耗品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "甜膩糖果 SICKLY SWEET CANDY", "category": "消耗品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "史萊姆汁液 SLIME JUICE", "category": "消耗品", "stock": "大量", "cost": "25 CCP" },
        { "item_id": "蜘蛛毒液蘋果酒 SPIDER VENOM CIDER", "category": "消耗品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "死亡花束 DEATHLY BOUQUET", "category": "新奇物品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "假牙 FALSE TEETH", "category": "新奇物品", "stock": "大量", "cost": "35 CCP" },
        { "item_id": "高級神秘南瓜盒 GREATER MYSTERY PUMPKIN BOX", "category": "新奇物品", "stock": "大量", "cost": "每個 50 CCP 或 5 個 200 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（藍色） HEADLESS HORSEMAN BOBBLEHEAD (BLUE)", "category": "新奇物品", "stock": "售罄", "cost": "25 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（綠色） HEADLESS HORSEMAN BOBBLEHEAD (GREEN)", "category": "新奇物品", "stock": "售罄", "cost": "25 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（粉色） HEADLESS HORSEMAN BOBBLEHEAD (PINK)", "category": "新奇物品", "stock": "售罄", "cost": "25 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（紫色） HEADLESS HORSEMAN BOBBLEHEAD (PURPLE)", "category": "新奇物品", "stock": "售罄", "cost": "25 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（紅色） HEADLESS HORSEMAN BOBBLEHEAD (RED)", "category": "新奇物品", "stock": "限量", "cost": "25 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（黃色） HEADLESS HORSEMAN BOBBLEHEAD (YELLOW)", "category": "新奇物品", "stock": "售罄", "cost": "25 CCP" },
        { "item_id": "彈出式稻草人 POP-UP SCARECROW", "category": "新奇物品", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "神秘南瓜盒 MYSTERY PUMPKIN BOX", "category": "新奇物品", "stock": "大量", "cost": "每個 25 CCP 或 5 個 100 CCP" },
        { "item_id": "神秘骷髏 MYSTERY SKULL", "category": "新奇物品", "stock": "大量", "cost": "每個 75 CCP 或 5 個 300 CCP" },
        { "item_id": "南瓜撲克牌 PUMPKIN PLAYING CARDS", "category": "新奇物品", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "殭屍皮 ZOMBIE SKIN", "category": "新奇物品", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "血咒 BLOOD CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "骨刃 BONE BLADE", "category": "附魔", "stock": "限量", "cost": "300 CCP" },
        { "item_id": "奇美拉詛咒 CHIMERA CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "邪能詛咒 FEL CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "鬼魅詛咒 GHOSTLY CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "利維坦詛咒 LEVIATHAN CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "機械融合 MACHINE BONDING", "category": "附魔", "stock": "限量", "cost": "300 CCP" },
        { "item_id": "心靈詛咒 MIND CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "不死詛咒 UNDEAD CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "虛空詛咒 VOID CURSE", "category": "附魔", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "衰弱詛咒 WEAKENING CURSE", "category": "附魔", "stock": "限量", "cost": "300 CCP" },
        { "item_id": "防腐血清 ANTI-DECAY SERUM", "category": "通用", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "空白墓碑 BLANK TOMBSTONE", "category": "通用", "stock": "大量", "cost": "20 CCP" },
        { "item_id": "雕刻工具 CARVING TOOLS", "category": "通用", "stock": "大量", "cost": "25 CCP" },
        { "item_id": "鏈提燈 CHAIN-O-LANTERN", "category": "通用", "stock": "限量", "cost": "250 CCP" },
        { "item_id": "腐蝕之血 CORROSIVE BLOOD", "category": "通用", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "機械之血 MACHINE BLOOD", "category": "通用", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "惡夢燃料 NIGHTMARE FUEL", "category": "通用", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "毒藥壺 PITCHER OF POISONS", "category": "通用", "stock": "限量", "cost": "150 CCP" },
        { "item_id": "劇毒生態瓶 POISONOUS TERRARIUM", "category": "通用", "stock": "限量", "cost": "500 CCP" },
        { "item_id": "便攜棺材 PORTABLE COFFIN", "category": "通用", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "骷髏鑰匙 SKELETON KEY", "category": "通用", "stock": "限量", "cost": "350 CCP" },
        { "item_id": "狡詐之袋 SLY BAG", "category": "通用", "stock": "稀缺", "cost": "350 CCP" },
        { "item_id": "折磨之釘 TORMENTING NAILS", "category": "通用", "stock": "大量", "cost": "每個 15 CCP 或 5 個 50 CCP" },
        { "item_id": "柳枝蠟燭 WICKER CANDLE", "category": "通用", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "折磨鎖鏈 CHAINS OF TORMENT", "category": "獨特物品", "stock": "稀缺", "cost": "500 CCP" },
        { "item_id": "隱形床單 INVISIBLE SHEET", "category": "獨特物品", "stock": "稀缺", "cost": "300 CCP" },
        { "item_id": "糖果袋 TREAT BAG", "category": "獨特物品", "stock": "稀缺", "cost": "500 CCP" },
        { "item_id": "密文齒輪 CIPHERS", "category": "獨特物品", "stock": "獨特", "cost": "100 CCP" }
      ],
      "shop-market": [
        { "item_id": "牛革鞭 BOVINE BULLWHIP", "category": "武器裝備", "stock": "限量", "cost": "300 CCP" },
        { "item_id": "獨眼巨人眼 CYCLOPS EYE", "category": "武器裝備", "stock": "限量", "cost": "300 CCP" },
        { "item_id": "地獄火箭矢 HELLFIRE ARROWS", "category": "武器裝備", "stock": "限量", "cost": "5 支 400 CCP" },
        { "item_id": "巫妖腸線 LICH’S GUT STRING", "category": "武器裝備", "stock": "限量", "cost": "350 CCP" },
        { "item_id": "鬼響鞭 RATTLE WHIP", "category": "武器裝備", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "蠍尾鞭 SCORPION TAIL", "category": "武器裝備", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "骷髏胸甲 SKELETAL BREASTPLATE", "category": "武器裝備", "stock": "稀缺", "cost": "500 CCP" },
        { "item_id": "脊骨巨劍 SPINAL BLADE", "category": "武器裝備", "stock": "限量", "cost": "250 CCP" },
        { "item_id": "人頭杖 STAFF OF HUMAN HEADS", "category": "武器裝備", "stock": "限量", "cost": "400 CCP" },
        { "item_id": "吸血鬼之淚 VAMPIRE TEARS", "category": "消耗品", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "吸血鬼之牙 VAMPIRIC TOOTH", "category": "消耗品", "stock": "限量", "cost": "200 CCP" },
        { "item_id": "液態金屬 LIQUID METAL", "category": "詛咒", "stock": "限量", "cost": "1000 CCP" },
        { "item_id": "南瓜血 PUMPKIN BLOOD", "category": "詛咒", "stock": "限量", "cost": "1000 CCP" },
        { "item_id": "稻草人之血 SCARECROW BLOOD", "category": "詛咒", "stock": "限量", "cost": "1000 CCP" },
        { "item_id": "蛇血 SNAKES BLOOD", "category": "詛咒", "stock": "限量", "cost": "1000 CCP" },
        { "item_id": "獨角獸之血 UNICORN BLOOD", "category": "詛咒", "stock": "限量", "cost": "1000 CCP" },
        { "item_id": "吸血鬼之血 VAMPIRES BLOOD", "category": "詛咒", "stock": "限量", "cost": "1000 CCP" },
        { "item_id": "狼人之血 WEREWOLVES BLOOD", "category": "詛咒", "stock": "限量", "cost": "1000 CCP" },
        { "item_id": "石像鬼粉 GROUND GARGOYLE", "category": "通用", "stock": "限量", "cost": "500 CCP" },
        { "item_id": "妖精翅膀粉 GROUND PIXIE WINGS", "category": "通用", "stock": "限量", "cost": "500 CCP" },
        { "item_id": "肉鑰 MEAT KEY", "category": "通用", "stock": "獨特", "cost": "1000 CCP" },
        { "item_id": "骷髏馬雕像 SKELETON HORSE IDOL", "category": "通用", "stock": "稀缺", "cost": "1250 CCP" },
        { "item_id": "泰拉毒液 TERRA POISON", "category": "通用", "stock": "限量", "cost": "500 CCP" },
        { "item_id": "拷問工具 TORTURERS TOOLS", "category": "通用", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "邪惡之水 UNHOLY WATER", "category": "通用", "stock": "限量", "cost": "100 CCP" },
        { "item_id": "牛環 BULL RING", "category": "獨特物品", "stock": "稀缺", "cost": "500 CCP" },
        { "item_id": "火藥鼠 GUNPOWDER RAT", "category": "獨特物品", "stock": "稀缺", "cost": "1000 CCP" },
        { "item_id": "盒中瘟疫 POX IN A BOX", "category": "獨特物品", "stock": "稀缺", "cost": "500 CCP" },
        { "item_id": "黯淡戒指 TARNISHED RING", "category": "獨特物品", "stock": "稀缺", "cost": "300 CCP" }
      ],
    "shop-restaurant": [
        { "item_id": "100% 火蜥蜴汁 100% JUICE OF FIRE NEWT", "category": "飲品Drinks", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "大釜潘趣酒 CAULDRON PUNCH", "category": "飲品Drinks", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "黑烏鴉乾燥腳 DRIED FEES OF BLACK CROW", "category": "飲品Drinks", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "未過濾毒藥 UNFILTERED POISON", "category": "飲品Drinks", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "女巫藥水 WITCHES POTION", "category": "飲品Drinks", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "災難餅乾 CATASTROPHIC COOKIES", "category": "零食Snacks", "stock": "大量", "cost": "5 塊 10 CCP" },
        { "item_id": "傷亡玉米 CASUALTY CORN", "category": "零食Snacks", "stock": "大量", "cost": "每包 5 CCP" },
        { "item_id": "食屍鬼椒鹽捲餅 GHOUL PRETZELS", "category": "零食Snacks", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "綠色油脂玉米 GREEN GRIZZLE CORN", "category": "零食Snacks", "stock": "大量", "cost": "每包 5 CCP" },
        { "item_id": "風味糖果玉米 FLAVORED CANDY CORN", "category": "零食Snacks", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "果凍南瓜 JELLY PUMPKINS", "category": "零食Snacks", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "仙塵 PIXIE DUST", "category": "零食Snacks", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "死神薯片 REAPER CHIPS", "category": "零食Snacks", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "蝙蝠翅膀 BATTY BAT WINGS", "category": "正餐Meals", "stock": "大量", "cost": "25 CCP" },
        { "item_id": "定罪麵包盅 CONDEMNED COB LOAF", "category": "正餐Meals", "stock": "大量", "cost": "30 CCP" },
        { "item_id": "怪物肉丸 MONSTER MEAT BALLS", "category": "正餐Meals", "stock": "大量", "cost": "30 CCP" },
        { "item_id": "蟒蛇薯塊 PYTHON POTATO’S", "category": "正餐Meals", "stock": "大量", "cost": "20 CCP" },
        { "item_id": "煙燻牛頭怪 SMOKED MINOTAUR", "category": "正餐Meals", "stock": "大量", "cost": "40 CCP" },
        { "item_id": "肋排 SPARE RIBS", "category": "正餐Meals", "stock": "大量", "cost": "5 根肋骨 40 CCP" },
        { "item_id": "辣脊椎 SPICY SPINES", "category": "正餐Meals", "stock": "大量", "cost": "25 CCP" },
        { "item_id": "怪趣拼盤 SPOOKUTERIE BOARD", "category": "正餐Meals", "stock": "大量", "cost": "每玩家 30 CCP (最少 3 人)" },
        { "item_id": "有毒通心粉 TOXIC MAC", "category": "正餐Meals", "stock": "大量", "cost": "25 CCP" },
        { "item_id": "黑天鵝絨紙杯蛋糕 BLACK VELVET CUPCAKES", "category": "甜點Desserts", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "血腥天鵝絨紙杯蛋糕 BLOODY VELVET CUPCAKES", "category": "甜點Desserts", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "腐蝕性紙杯蛋糕 CAUSTIC CUPCAKES", "category": "甜點Desserts", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "被詛咒的紙杯蛋糕 CURSED CUPCAKES", "category": "甜點Desserts", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "毒蘋果 POISONED APPLES", "category": "甜點Desserts", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "尖叫芝士布朗尼 SCREAM-CHEESE BROWNIE", "category": "甜點Desserts", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "蛇咬切片 SNAKEBITE SLICE", "category": "甜點Desserts", "stock": "大量", "cost": "10 CCP" }
      ],
      "shop-bobblehead": [
        { "item_id": "蝙蝠 BAT", "category": "普通款Generic", "stock": "大量", "cost": "20 CCP", "buyback_price": "5 CCP" },
        { "item_id": "幽靈 GHOST", "category": "普通款Generic", "stock": "大量", "cost": "20 CCP", "buyback_price": "10 CCP" },
        { "item_id": "希德搖頭娃娃 SID’S BOBBLEHEAD", "category": "普通款Generic", "stock": "無", "cost": "5 CCP", "buyback_price": "不值錢" },
        { "item_id": "骷髏 SKEEN", "category": "普通款Generic", "stock": "大量", "cost": "20 CCP", "buyback_price": "5 CCP" },
        { "item_id": "蜘蛛 SPIDER", "category": "普通款Generic", "stock": "大量", "cost": "20 CCP", "buyback_price": "10 CCP" },
        { "item_id": "魅魔 SUCCUBUS", "category": "普通款Generic", "stock": "大量", "cost": "20 CCP", "buyback_price": "15 CCP" },
        { "item_id": "殭屍 ZOMBIE", "category": "普通款Generic", "stock": "大量", "cost": "20 CCP", "buyback_price": "10 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（藍色） HEADLESS HORSEMAN BOBBLEHEAD (BLUE)", "category": "季節款Seasonal", "stock": "售罄", "cost": "-", "buyback_price": "100 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（綠色） HEADLESS HORSEMAN BOBBLEHEAD (GREEN)", "category": "季節款Seasonal", "stock": "售罄", "cost": "-", "buyback_price": "125 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（粉色） HEADLESS HORSEMAN BOBBLEHEAD (PINK)", "category": "季節款Seasonal", "stock": "售罄", "cost": "-", "buyback_price": "75 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（紫色） HEADLESS HORSEMAN BOBBLEHEAD (PURPLE)", "category": "季節款Seasonal", "stock": "售罄", "cost": "-", "buyback_price": "100 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（紅色） HEADLESS HORSEMAN BOBBLEHEAD (RED)", "category": "季節款Seasonal", "stock": "限量", "cost": "25 CCP", "buyback_price": "15 CCP" },
        { "item_id": "無頭騎士搖頭娃娃（黃色） HEADLESS HORSEMAN BOBBLEHEAD (YELLOW)", "category": "季節款Seasonal", "stock": "售罄", "cost": "-", "buyback_price": "75 CCP" },
        { "item_id": "亞當 ADAM", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "30 CCP" },
        { "item_id": "阿嘉莎 AGATHA", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "20 CCP" },
        { "item_id": "傲霜女巫姊妹三人組 ALABASTER WITCH SISTERS TRIO", "category": "特別款Special", "stock": "限量", "cost": "120 CCP", "buyback_price": "55 CCP" },
        { "item_id": "阿納巨蟒 ANACONDA", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "15 CCP" },
        { "item_id": "阿斯特洛斯之樹 ASTEROTH’S TREE", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "10 CCP" },
        { "item_id": "弗萊徹 FLETCHER", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "5 CCP" },
        { "item_id": "拉西安娜 LACIANA", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "25 CCP" },
        { "item_id": "雷恩 LAINE", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "35 CCP" },
        { "item_id": "拉米娜 LAMINA", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "15 CCP" },
        { "item_id": "拉札拉克 LAZARAK", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "15 CCP" },
        { "item_id": "L.E.A.D. 南瓜終結者 L.E.A.D. PUMPKINATOR", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "50 CCP" },
        { "item_id": "莉絲貝 LISBETH", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "35 CCP" },
        { "item_id": "里希登斯坦領主 LORD LICHTENSTEIN", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "20 CCP" },
        { "item_id": "洛恩 LORNE", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "10 CCP" },
        { "item_id": "離途沼澤 LOSTFOOT’S BOG", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "5 CCP" },
        { "item_id": "盧卡斯 LUCAS", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "20 CCP" },
        { "item_id": "奧列格 OLEG", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "5 CCP" },
        { "item_id": "奧菲莉婭 OPHELIA", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "40 CCP" },
        { "item_id": "奧瑞莎 ORISA", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "30 CCP" },
        { "item_id": "奧瑞克 ORRICK", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "20 CCP" },
        { "item_id": "奧斯瓦多 OSVALDO", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "5 CCP" },
        { "item_id": "威廉 WILLIAM", "category": "特別款Special", "stock": "限量", "cost": "50 CCP", "buyback_price": "20 CCP" },
        { "item_id": "搖頭娃娃靈魂分離器 BOBBLEHEAD SOUL SEPARATOR", "category": "工具", "stock": "獨特", "cost": "5000 CCP", "buyback_price": "-" },
        { "item_id": "保護盒 PROTECTIVE BOX", "category": "工具", "stock": "大量", "cost": "10 CCP", "buyback_price": "-" }
      ],
      "shop-curio": [
        { "item_id": "骨鏢 BONE DARTS", "category": "武器裝備", "stock": "大量", "cost": "20 支 5 CCP" },
        { "item_id": "小丑錘 CLOWN HAMMER", "category": "武器裝備", "stock": "限量", "cost": "50 CCP" },
        { "item_id": "假花 FAKE FLOWER", "category": "武器裝備", "stock": "限量", "cost": "60 CCP" },
        { "item_id": "滴血餅乾 BLEEDING BISCUIT", "category": "消耗品", "stock": "大量", "cost": "8 CCP" },
        { "item_id": "棉花糖蘋果酒 COTTON CANDY CIDER", "category": "消耗品", "stock": "大量", "cost": "5V CCP" },
        { "item_id": "棉花糖玉米 COTTON CANDY CORN", "category": "消耗品", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "眼球棒 EYEBALL ON A STICK", "category": "消耗品", "stock": "大量", "cost": "3 CCP" },
        { "item_id": "炸手指 FRIED FINGERS", "category": "消耗品", "stock": "大量", "cost": "8 CCP" },
        { "item_id": "腎結石玉米糖 KIDNEY CORN", "category": "消耗品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "瘟疫花生 PESTILENT PEANUTS", "category": "消耗品", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "驚嚎冰棒 SCREAMSICLE", "category": "消耗品", "stock": "大量", "cost": "8 CCP" },
        { "item_id": "尖叫汽水 SODA SCREAM", "category": "消耗品", "stock": "大量", "cost": "5 CCP" },
        { "item_id": "電擊太妃糖 ZAPPY TAFFY", "category": "消耗品", "stock": "大量", "cost": "5 根 5 CCP" },
        { "item_id": "殭屍玉米 ZOMBIE CORN", "category": "消耗品", "stock": "大量", "cost": "15 CCP" },
        { "item_id": "女妖毛絨玩偶 BANSHEE PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "80 CCP" },
        { "item_id": "骨製煙花 BONEWORK", "category": "新奇物品", "stock": "大量", "cost": "每個 5 CCP 或 10 個 25 CCP" },
        { "item_id": "烏鴉毛絨玩偶 CROW PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "5 CCP" },
        { "item_id": "幽靈毛絨玩偶 GHOST PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "80 CCP" },
        { "item_id": "食屍鬼毛絨玩偶 GHOUL PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "20 CCP" },
        { "item_id": "老鼠毛絨玩偶 RAT PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "5 CCP" },
        { "item_id": "骷髏毛絨玩偶 SKELETON PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "10 CCP" },
        { "item_id": "希德搖頭娃娃 SID’S BOBBLEHEAD", "category": "新奇物品", "stock": "大量", "cost": "50 CCP" },
        { "item_id": "蜘蛛毛絨玩偶 SPIDER PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "5L CCP" },
        { "item_id": "可疑的紅氣球 SUSPICIOUSLY RED BALLOON", "category": "新奇物品", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "蟾蜍氣球 TOAD BALLOON", "category": "新奇物品", "stock": "大量", "cost": "10 CCP" },
        { "item_id": "屍妖毛絨玩偶 WIGHT PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "60 CCP" },
        { "item_id": "殭屍毛絨玩偶 ZOMBIE PLUSHIE", "category": "新奇物品", "stock": "限量", "cost": "10 CCP" },
        { "item_id": "驚喜袋（小號） SHOW BAG (SMALL)", "category": "驚喜袋", "stock": "大量", "cost": "25 CCP" },
        { "item_id": "驚喜袋（中號） SHOW BAG (MEDIUM)", "category": "驚喜袋", "stock": "大量", "cost": "45 CCP" },
        { "item_id": "驚喜袋（大號） SHOW BAG (LARGE)", "category": "驚喜袋", "stock": "大量", "cost": "60 CCP" },
        { "item_id": "驚喜袋（特大號） SHOW BAG (EXTRA_LARGE)", "category": "驚喜袋", "stock": "大量", "cost": "75 CCP" }
      ]
    }
  },
  "tasks": {
    "categories": {
      "task-bounty": "鬼燈市集：達卡的懸賞告示牌",
      "task-contest": "餐館：貝拉的飲食競賽",
      "task-games": "詭異珍品：雜耍遊戲"
    },
    "items": {
      "task-bounty": [
        { "id": "bounty-001", "name_zh": "屍體化", "name_en": "Corpsified", "reward_str": "500 CCP", "desc_zh": "讓亞當異形怪的最後一擊由屍體工廠的陷阱造成。", "desc_en": "Have the final blow on Adam the Abomination be dealt by one of the corpse factories traps" },
        { "id": "bounty-002", "name_zh": "懦弱領主", "name_en": "Cowardly Lord", "reward_str": "1000 CCP", "desc_zh": "偷走里希登斯坦領主的煉金藥水，並在徹底擊敗他之前將里希登斯坦變成一隻雞。真是個膽小鬼。", "desc_en": "Steal Lord Lichtenstein’s alchemical potions and turn Lichtenstein into a chicken before defeating him outright. What a chicken." },
        { "id": "bounty-003", "name_zh": "顏色調換", "name_en": "Color Swapping", "reward_str": "1500 CCP", "desc_zh": "在同一場戰鬥遭遇中，僅使用冰凍傷害擊敗安柏傲霜女巫，僅使用火焰傷害擊敗紫晶傲霜女巫，並僅使用閃電傷害擊敗安漷傲霜女巫。", "desc_en": "Defeat Amber Alabaster using only cold damage, defeat Amethyst Alabaster using only fire damage and defeat Aqua Alabaster using only lightning damage during the same combat encounter." },
        { "id": "bounty-004", "name_zh": "匕首匕首", "name_en": "Dagger Dagger", "reward_str": "1000 CCP", "desc_zh": "僅使用匕首或匕首類型武器造成的傷害擊敗刀鋒兄弟艾歷克斯和阿克塞爾。盜賊們，我說得對吧。", "desc_en": "Defeat Alex and Axel, the Blade Brothers using only damage dealt by daggers or weapons with the dagger type. Rogues am I right." },
        { "id": "bounty-005", "name_zh": "自掘墳墓", "name_en": "Digging Your Own Grave", "reward_str": "1000 CCP", "desc_zh": "在掘墓者奧瑞克挖掘或至少在地下時，對他造成致命一擊。高效的埋葬。", "desc_en": "Get the killing blow on Orrick the Gravedigger while he is burrowed or at least under the ground. Efficient Burials." },
        { "id": "bounty-006", "name_zh": "火，火！", "name_en": "Fire, Fire!", "reward_str": "500 CCP", "desc_zh": "僅使用造成火焰傷害的攻擊擊敗亞當異形怪。燒焦了。", "desc_en": "Defeat Adam the Abomination using only attacks that deal Fire Damage. Burned." },
        { "id": "bounty-007", "name_zh": "滾出我的地盤，洛恩！", "name_en": "Get Off My Lorne", "reward_str": "1500 CCP", "desc_zh": "僅使用徒手打擊擊敗墓穴的洛恩。就像真正的武僧一樣。", "desc_en": "Defeat Lorne of the Tomb using only Unarmed Strikes. Just like a real monk." },
        { "id": "bounty-008", "name_zh": "斬首", "name_en": "Headless", "reward_str": "1000000 CCP", "desc_zh": "砍下無頭騎士的頭。", "desc_en": "Cut off the Horseman’s head." },
        { "id": "bounty-009", "name_zh": "縫合完畢", "name_en": "Left in Stiches", "reward_str": "500 CCP", "desc_zh": "僅在奧斯瓦多縫屍匠從他的「縫合完畢」能力中獲得所有五種增強後，才擊敗他。更可能是痛苦的發作。", "desc_en": "Defeat Osvaldo the Stitcher only after he has obtained all five augments from his Stitched Up ability. Fits of pain more likely." },
        { "id": "bounty-010", "name_zh": "南瓜爆炸", "name_en": "Punk-Splosion", "reward_str": "500 CCP", "desc_zh": "使用一個點燃的南瓜炸彈對南瓜之王拉札拉克造成致命一擊。", "desc_en": "Get the killing blow on Lazarak the Pumpkin King using a lit Pumpkin Bomb." },
        { "id": "bounty-011", "name_zh": "重新充能", "name_en": "Recharged", "reward_str": "1000 CCP", "desc_zh": "將 L.E.A.D. 南瓜終結者的生命值降至其起始總生命值的一半以下，然後僅使用火焰傷害將其治療回滿生命值，然後再徹底擊敗它。火焰吸收太棒了。", "desc_en": "Drop the L.E.A.D. Pumpkinator to below half of its starting total HP and then use only Fire damage to heal it back up to full health before defeating it outright. Fire Absorption is great." },
        { "id": "bounty-012", "name_zh": "劈砍木屑", "name_en": "Rip Rip Woodchip", "reward_str": "500 CCP", "desc_zh": "僅使用造成揮砍傷害的攻擊擊敗阿斯特洛斯之樹。砍砍。", "desc_en": "Defeat Asteroth’s Tree by using only attacks that inflict Slashing Damage. Chop chop" },
        { "id": "bounty-013", "name_zh": "銀器殺手", "name_en": "Silver Slayer", "reward_str": "500 CCP", "desc_zh": "僅使用鍍銀武器的攻擊擊敗虧月之人盧卡斯。", "desc_en": "Defeat Lucas of the Waning Moon using only attacks from silvered weapons." },
        { "id": "bounty-014", "name_zh": "沉沒感", "name_en": "Sinking Feeling", "reward_str": "500 CCP", "desc_zh": "在沉洞水面下游泳時，對沉洞阿納巨蟒造成最後一擊。", "desc_en": "Land the final blow on the Anaconda of the Sinkhole while swimming beneath the surface in the same sinkhole." },
        { "id": "bounty-015", "name_zh": "濺射傷害", "name_en": "Splash Damage", "reward_str": "1500 CCP", "desc_zh": "在受到莉絲貝誘惑魔女的「誘惑打擊」能力影響時擊敗她。", "desc_en": "Defeat Lisbeth the Temptress while under the effects of her Seductive Strike ability." },
        { "id": "bounty-016", "name_zh": "那是我的血", "name_en": "That’s My Blood", "reward_str": "1500 CCP", "desc_zh": "在被奧瑞莎凝血者擊倒並成功成為其「生命吸取」能力目標後，對她造成致命一擊。", "desc_en": "Get the killing blow on Orisa the Blood Curdler after being downed and successfully targeted by her Life Sucker ability." },
        { "id": "bounty-017", "name_zh": "網上戰士", "name_en": "Web Warrior", "reward_str": "500 CCP", "desc_zh": "在被蜘蛛女王拉西安娜的網束縛時，對她造成致命一擊。", "desc_en": "Land the killing blow on Laciana the Spider Queen while restrained by her webs." },
        { "id": "bounty-018", "name_zh": "你不是我", "name_en": "You’re Not Me", "reward_str": "1500 CCP", "desc_zh": "在受到雷恩完美主義者的「記憶竊取」和「完美鏡像」能力影響後，對她造成致命一擊。有兩個？", "desc_en": "Get the Killing blow on Laine the Perfectionist after you have been affected by her Memory Tap and Perfect Mirror Abilities. There’s two?" },
        { "id": "bounty-019", "name_zh": "你太自戀了", "name_en": "You’re So Vain", "reward_str": "500 CCP", "desc_zh": "戰鬥中沒有獵人可以對瘋狂少女阿嘉莎造成傷害。僅通過在她的巢穴中揭露鏡子來擊敗她。", "desc_en": "No hunter may deal damage to Agatha the Mad Maiden during the battle. Defeat her only by uncovering mirrors in her lair." }
      ],
      "task-contest": [
        { "id": "contest-001", "name_zh": "硫磺餅乾", "name_en": "Brimstone Biscuit", "cost_str": "30 CCP", "reward_id": "易燃紙 FICKLE FLAME", "desc_zh": "盛在一塊鐵板上，硫磺餅乾看起來像一大塊煤，其外殼上有發紅光的脈絡，不斷散發出熱氣。食物有 12 HP 和 16 AC。在它的回合，食物自動擊中玩家，造成 1D8 火焰傷害，因為它灼燒玩家。", "desc_en": "Served on a slab of iron, the brimstone biscuit looks like a large lump of coal with glowing red veins coursing through its shell that constantly emanates a haze of heat. The food has 12 HP and 16 AC. On its turn the food automatically hits the player with 1D8 Fire Damage as it burns the player." },
        { "id": "contest-002", "name_zh": "末日蘑菇", "name_en": "Doom Shroom", "cost_str": "40 CCP", "reward_id": "蓬蓬炸彈 PUFF BOMB", "desc_zh": "一個 2 英尺 x 2 英尺大的、看起來像皮革的蘑菇帽，盛在新鮮採摘的龍葵床上。我的意思是它看起來完全無害可食用。食物有 50 HP 和 3 AC。在它的回合，食物釋放孢子。當食物釋放孢子時，進食的玩家必須進行 DC13 的體質豁免，失敗則受到 1D10 毒素傷害，成功則傷害減半。即使你豁免成功，也不會獲得對此效果的免疫。", "desc_en": "A large 2 foot by 2 foot leathery looking mushroom cap served on bed of freshly picked nightshade. I mean it looks perfectly harmless to eat. The food has 50 HP and 3 AC. On its turn the food releases spores. When the food releases spores, the eating player must make a DC13 Constitution saving throw or be dealt 1D10 Poison Damage on a failed save or half as much on a successful save. You do not gain immunity to this effect if you succeed." },
        { "id": "contest-003", "name_zh": "淤泥啤酒", "name_en": "Ooze Booze", "cost_str": "20 CCP", "reward_id": "脊骨啤酒杯 SPINE STEIN", "desc_zh": "一杯豐盛的半加侖大杯，滿溢著黏稠的綠色液體，偶爾發出低沉的咕嚕聲。當你從桌子上拿起它時，你注意到溢出的液體會自己拉回杯子裡。食物有 15 HP 和 18 AC。在它的回合，食物用偽足自動擊中玩家，造成 1D8 鈍擊傷害。", "desc_en": "A hearty sized ½ gallon mug overflowing with a viscous green liquid that occasionally makes a low gurgling sound. As you pick it up from the table you take note that the overflowing fluid pulls itself back into the mug. The food has 15 HP and 18 AC. On its turn the food automatically hits the player with a pseudopod for 1D8 Bludgeoning damage." },
        { "id": "contest-004", "name_zh": "尖刺苔蘚沙拉", "name_en": "Spike Moss Salad", "cost_str": "15 CCP", "reward_id": "不死之勺 UNDEAD SPOON", "desc_zh": "一團看似無害的綠色苔蘚，盤子上淋著香醋。可惜的是，當你觸摸它時，它立刻變成了一個尖刺球。食物有 30 HP 和 5 AC。在它的回合，食物自動擊中玩家，造成 1D6 穿刺傷害，因為它刺傷玩家。", "desc_en": "A messy clump of seemingly harmless green moss that is plated up with a balsamic drizzle. Too bad that it instantly turns into a ball of spikes when you touch it. The food has 30 HP and 5 AC. On its turn the food automatically hits the player with 1D6 Piercing Damage as it spikes the player." },
        { "id": "contest-005", "name_zh": "扼殺魷魚", "name_en": "The Strangler Squid", "cost_str": "25 CCP", "reward_id": "惡魔之鹽 DEMON SALT", "desc_zh": "一根粗壯的、四英尺長的烤觸手，聞起來有黃油和海鹽的味道。如果觸手沒有在盤子上移動，它可能是一頓豐盛的大餐。食物有 25 HP 和 12 AC。在它的回合，食物自動擊中玩家，造成 1D10 鈍擊傷害，因為它扼殺玩家。", "desc_en": "A single thick, four foot long roasted tentacle that smells of butter and sea salt. It probably would be a hearty feast if the tentacle wasn’t moving around on the plate. The food has 25 HP and 12 AC.On its turn the food automatically hits the player with 1D10 Bludgeoning Damage as it strangles the player." },
        { "id": "contest-006", "name_zh": "吸血鬼水蛭", "name_en": "The Vampire Leech", "cost_str": "50 CCP", "reward_id": "黏稠袋 GLUTINOUS BAG", "desc_zh": "一條宴會尺寸的油炸水蛭，嘴裡長滿了鋒利的吸血鬼牙齒。吸血鬼水蛭會試圖在你把它吃到死之前把你吸乾。食物有 30 HP 和 10 AC。在它的回合，食物自動擊中玩家，造成 1D6 穿刺傷害，並恢復那麼多生命值，因為它從玩家身上吸取生命。", "desc_en": "A full banquet sized deep fried leech that has a mouth full of razor sharp vampire teeth. The vampire leech is going to try and suck you dry before you can eat it to death. The food has 30 HP and 10 AC. On its turn the food automatically hits the player with 1D6 Piercing Damage and regains that many Hit Points as it sucks the life from the player." },
        { "id": "contest-007", "name_zh": "帝王蜘蛛蟹宴（4-5名玩家）", "name_en": "King Spider Crab Banquet", "cost_str": "120 CCP", "reward_id": "蜘蛛蟹護符 SPIDER CRAB CHARM", "desc_zh": "一個供整個隊伍嘗試生存的特殊飲食競賽。一隻桌子大小的清蒸蜘蛛蟹，絕對還活著，並且不想成為你的餐點。享用吧！對於這個挑戰，根據正常情況為每個玩家單獨擲先攻。食物有 80 HP 和 15 AC。在它的回合，食物用它的蜘蛛蟹爪自動擊中每個玩家，造成 1D8 揮砍和 1D8 穿刺傷害。", "desc_en": "A special eating competition for a whole party to try and survive. A small table sized steamed spider crab that is most definitely still alive and doesn’t want to be you meal. Enjoy! For this challenge roll initiative for each player separately as per normal. The food has 80 HP and 15 AC. On its turn the food automatically hits each player with its spider crab claws for 1D8 Slashing and 1D8 Piercing damage." }
      ],
      "task-games": [
        { "id": "game-001", "name_zh": "膀胱爆破", "name_en": "Bladder Pop", "cost_str": "10 CCP", "desc_zh": "玩家獲得 3 支骨鏢，投向一面充滿膨脹膀胱的牆。對於每支飛鏢，玩家必須對膀胱的 8 AC 進行一次遠程攻擊檢定。成功命中則一個膀胱被戳破。對於每個被戳破的膀胱，玩家必須擲 1D10 並將結果相加來計算玩家的分數。", "desc_en": "The player is given 3 bone darts to throw at a wall of inflated bladders. For each dart players must make a ranged attack roll against the 8 AC of the bladders. A bladder is popped on a successful hit. For each bladder popped the player must roll 1D10 and add the results together to calculate the players score." },
        { "id": "game-002", "name_zh": "肋骨投擲", "name_en": "Rib Toss", "cost_str": "10 CCP", "desc_zh": "向玩家提供 6 根彎曲的肋骨，嘗試將其套在幾根脊椎骨中的一根上。對於每根投出的肋骨，玩家進行一次臨時遠程武器攻擊。玩家將根據每次攻擊檢定的成功程度得分。10 或更高得 1 分，14 或更高得 3 分，17 或更高得 5 分。將它們全部相加得到獎品。", "desc_en": "The player is provided with 6 curved ribs to attempt at tossing around one of several spines. For each rib tossed the player makes an improvised ranged weapon attack. The player will score depending on how successful each attack roll is. 10 or higher is 1 point, 14 or higher is 3 points and 17 or higher is 5 points. Add them all together for the prize." },
        { "id": "game-003", "name_zh": "腦力深潛", "name_en": "Brain Bobbing", "cost_str": "5 CCP", "desc_zh": "玩家必須頭朝下潛入一個黏糊糊的、你不想知道裡面是什麼的桶裡，並用他們的嘴或等效器官抓住一個大腦。玩家必須首先成功通過 DC13 的體質豁免，否則會因厭惡而退縮並失敗遊戲。如果成功，玩家必須用他們的嘴對大腦的 10 AC 進行一次臨時近戰攻擊。如果玩家沒有溺水或把頭縮回來，他們可以進行多次嘗試來獲取一個大腦。一旦檢回一個大腦，玩家擲 3D8，這將代表他們的分數和大腦大小。", "desc_en": "Players must plunge headfirst into a slimy barrel of you don’t want to know what and grab a brain with their mouth or equivalent orifice. The player must first succeed on a DC13 Constitution saving throw or reel back in disgust and fail the game. If they are successful, the player must make an improvised melee attack with their mouth against the brains 10 AC. The player may make multiple attempts to get a brain if they don’t drown or pull their head out. Once a brain is retrieved the player rolls 3D8 which will represent their points and the brain size." },
        { "id": "game-004", "name_zh": "噩夢釣魚", "name_en": "Nightmare Fishing", "cost_str": "15 CCP", "reward_id": "海洋靈魂 SEA SOUL", "desc_zh": "玩家必須將他們的整個手臂或等效附肢放入一池漆黑黏稠的液體中。一旦低於水面，他們就無法再看到手臂，但能感覺到有東西撞擊它、觸摸和輕咬他們。玩家必須根據下表從最簡單的 DC 開始，成功通過越來越困難的感知豁免，以克服恐懼並將手臂保持在液體中。他們堅持的時間越長，水下有生物附著在他們手臂上的感覺就會變得越強烈。根據下表，將根據他們能將手臂保持在 liquid 中的時間長短來授予分數。如果玩家豁免失敗，他們還會在相當於他們試圖通過的 DC 的分鐘數內陷入恐慌狀態。此外，成功通過 DC20 的玩家還將因其勇氣獲得一個額外獎品，名為「海洋靈魂」的物品。\n\nWIS DC | Points\n---|---\n- | 0\nDC8 | 5\nDC10 | 10\nDC12 | 15\nDC14 | 20\nDC16 | 25\nDC18 | 30\nDC20 | 31+", "desc_en": "The player must lower their entire arm or equivalent appendage into a pitch black pool of viscous liquid. Once below the water’s surface they can no longer see the arm, but can feel things bumping into it, touching and nibbling at them. The player must succeed on increasingly difficult Wisdom saving throws tarting with the easiest DC on the table below in order to overcome their fear and keep their arm in the liquid. The longer they last the greater the sensations of creatures latching onto their arm beneath the surface will become. Points will be awarded based on how long they can keep their arm in the liquid as per the below table. If a player fails a saving throw they will also become Frightened for a number of minutes equal to the DC they were attempting to pass. Additionally players who succeed DC20 will also be given an additional prize in the form of an item called a Sea Soul for their bravery.\n\nWIS DC | Points\n---|---\n- | 0\nDC8 | 5\nDC10 | 10\nDC12 | 15\nDC14 | 20\nDC16 | 25\nDC18 | 30\nDC20 | 31+" }
      ]
    }
  }
};
